### ISSUE TITLE
Mailing list integration

### ISSUE THREAD

**Issue by roper79** [DataStewardshipWizard/dsw-common#119]
- [ ] UI form consent during registration: "I want to receive notifications about DSW updates and important technical messages"
- [ ] UI update the subscription (Profile Edit)
- [ ] server: store and manage the subscription via MailChimp
- [ ] server: store and manage the subscription in DB

**Comment by vknaisl** [comment]
Moved to Jira: https://ds-wizard.atlassian.net/browse/DSW-83
