### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by vknaisl** [DataStewardshipWizard/dsw-common#24]
# Changes:

## Client
- [x] Create issue
- [x] Show list of unresolved issues for each question in questionnaire

## Server 
- [x] Endpoints for list and create feedbacks
- [x] Connect to GitHub
- [x] Create refresh
- [x] Set up cron job for refresh
- [x] Test
- [x] API Docs

**Comment by janslifka** [comment]
For each organization deployment:
- Administrator creates a GitHub repository for issues
- She also creates a service account
- Access token and repository in configuration
- Backend uses GitHub API to create issues in the reposizoty

**Comment by MarekSuchanek** [comment]
## Configuration

I would consider having GitHub repository + token in configuration file vs. configuration directly in the Wizard. It is kinda tricky... 

- In file = if repository name or token is changed, DSW needs to be restarted
- In app = all admins have access to secret token, could be dangerous, but easier to change on the fly

## Giving feedback

1. User fills in feedback form
2. DSW sends [POST /repos/:owner/:repo/issues](https://developer.github.com/v3/issues/#create-an-issue) with some predefined label(s) and template (including the question UUID, title, and other related information that is needed - no information about the user). This request uses **token** in Authorization header.
3. As response DSW gets issue as JSON including it's ID - stores it in the database and provide a link to the user that just gave feedback.

## Displaying status of issues

### Periodic updates

1. Periodically, DSW checks issues stored in the database if are not closed/reopened. 
    - [GET /repos/:owner/:repo/issues](https://developer.github.com/v3/issues/#list-issues) is good for this task... Probably much better than doing it one by one.
2. If the issue is closed, then update record in the database.

### Hooks

1. Administrator sets up a hook for the repository (can be done with some DSW functionality - click on button to create the hook). The hook should have allowed "Issues" and should be [secured](https://developer.github.com/webhooks/securing/) - the secret needs to be configured in DSW.
2. DSW listens for POST requests on some defined URL (e.g. `/github-hooks`).
2. When something happens with issue, DSW will be informed with [issues event](https://developer.github.com/v3/activity/events/types/#issuesevent). For now, it should work just with actions *closed* and *reopened* and change the record in the database.

## Haskell support

There are few libraries that support GitHub API in Haskell... most promising (maintained, useful?) are:

- http://hackage.haskell.org/package/github
- http://hackage.haskell.org/package/github-webhooks

## Conclusion

- There will be 3 new configuration items: repository, token, webhook secret
- Functionality:
  - Submit feedback as issue to GitHub & store issue in database
  - Show opened issues related to the question
  - Check issues if their state (open/closed) is changed

**Comment by vknaisl** [comment]
Great proposal, @MarekSuchanek. Could you please set up some repository for our staging and production environment and send me tokens? Thanks

**Comment by MarekSuchanek** [comment]
Since it will be account and repositories for the global DSW instance, let's discuss the naming first... 

- DSWGlobal
- DSWGlobal/dsw
- DSWGlobal/dsw-staging (can be private...)

**Comment by vknaisl** [comment]
# API Proposal

## GET /feedbacks
### Response - 200 Ok
```
[
  {
     "questionUuid": "d8a4bcb0-a203-4b21-b06f-08fa2cff775b"
     "title": "Provide more descriptive content"
     "content": "I'm not very satisfied with a description of this question"
  }
]
```

## POST /feedbacks
### Request
```
{
     "questionUuid": "d8a4bcb0-a203-4b21-b06f-08fa2cff775b"
     "title": "Provide more descriptive content"
     "content": "I'm not very satisfied with a description of this question"
}
```
### Response - 201 Created
```
{
     "questionUuid": "d8a4bcb0-a203-4b21-b06f-08fa2cff775b"
     "title": "Provide more descriptive content"
     "content": "I'm not very satisfied with a description of this question"
}
```

## GET /feedbacks/{questionUuid}
### Response - 200 Ok
```
{
     "questionUuid": "d8a4bcb0-a203-4b21-b06f-08fa2cff775b"
     "title": "Provide more descriptive content"
     "content": "I'm not very satisfied with a description of this question"
}
```

**Comment by MarekSuchanek** [comment]
Found a bug: link uses different ID of issue (totally unique) and not ID of repository issue to be used (we had some super long like 3912... but it should has to be just 16.

**Comment by vknaisl** [comment]
@MarekSuchanek bug with issuedId is fixed
