### ISSUE TITLE
Costs computation

### ISSUE THREAD

**Issue by roper79** [DataStewardshipWizard/dsw-common#88]
- IS Item: #7 
- Related to: #92 

- [x] Separate **DSW Evaluator** service
  - Implement: https://docs.google.com/spreadsheets/d/1IGW0cA549Nn21HV5139B1v1ioRNDej1PfjqmBQ0kjNM/edit#gid=0
  - The config (right part) can be in deployment configuration
  - The user can use the service in simplified manner directly
  - (_update_) Implementation: https://github.com/DataStewardshipWizard/storage-costs-evaluator
- [x] Test & deploy the **DSW Evaluator** service
  - Deployed: http://storage-costs.evaluator.dsw.fairdata.solutions
- [ ] Integrator of evaluator 
- [ ] Connect to DS Wizard KM & reporting

**Comment by MarekSuchanek** [comment]
I will implement the spreadsheet as simple evaluator service: https://github.com/DataStewardshipWizard/storage-costs-evaluator/pull/1

@rwwh, during the rewriting to Haskell, some questions emerged:

- Why only less than 30 HDDs allows shareable servers? (cell F15)
- Should be rack size (number of servers in rack) configurable instead of hardcoded 6? (cell F17)
- What are the values 200 and 0.05 for computing tape operator hours? (cell I13)
- Should be number of tapes threshold after that index is needed configurable instead of hardcoded 5? (cell I14)
- In UPS costs, why *space needed* is multiplied by *electricity cost* but *number of servers* is multiplied by *server power*? Shouldn't be there *HDD power* instead of *electricity cost*? (cell I26)

**Comment by rwwh** [comment]
1) The idea was that if you can fill an entire storage server for yourself, that it no longer makes sense to share it. That may have changed in the mean time.
2) Definitely make it configurable if you want. I just put a practical number in there, looking at the density in a compute center I visited. The servers may total only 4 U, but they were always running into other limits.
3) Probably 200 days per year, each taking 0.05 hours to get the right tape from the safe, exchange the tape and put the written tape into the safe. Too long ago to be sure.
4) Does not harm to parameterize it; I'm not sure where it is used any more.
5) Yes, it should be M8 instead of M7. That makes quite a difference in the result, so maybe some of the parameters need to be rechecked with experts in a computer center (eg M25)

**Comment by vknaisl** [comment]
Moved to Jira: https://ds-wizard.atlassian.net/browse/DSW-76
